--liquibase formatted sql

--changeset todo-db:tododb-1.1 stripComments:true

--------------------------------------------------------
-- Copyright 2009-2016, Acciente LLC
--
-- Acciente LLC licenses this file to you under the
-- Apache License, Version 2.0 (the "License"); you
-- may not use this file except in compliance with the
-- License. You may obtain a copy of the License at
--
--     http://www.apache.org/licenses/LICENSE-2.0
--
-- Unless required by applicable law or agreed to in
-- writing, software distributed under the License is
-- distributed on an "AS IS" BASIS, WITHOUT WARRANTIES
-- OR CONDITIONS OF ANY KIND, either express or implied.
-- See the License for the specific language governing
-- permissions and limitations under the License.
--------------------------------------------------------

-- ----------------------------------------------------------------------
-- Sequences
-- ----------------------------------------------------------------------

CREATE SEQUENCE TODO.TodoItemId AS BIGINT START WITH 1 INCREMENT BY 1;

-- ----------------------------------------------------------------------
-- Tables
-- ----------------------------------------------------------------------

CREATE TABLE TODO.TodoUser (
    Email VARCHAR(128)  NOT NULL,
    CONSTRAINT PK_User PRIMARY KEY (Email)
);

CREATE INDEX IX_TodoUser_Email ON TODO.TodoUser (Email);

CREATE TABLE TODO.TodoItem (
    Id BIGINT GENERATED BY DEFAULT AS SEQUENCE TODO.TodoItemId NOT NULL,
    Title VARCHAR(128)  NOT NULL,
    Completed BOOLEAN  NOT NULL,
    CONSTRAINT PK_TodoItem PRIMARY KEY (Id)
);

CREATE INDEX IX_TodoItem_Id ON TODO.TodoItem (Id);
CREATE INDEX IX_TodoItem_Completed ON TODO.TodoItem (Completed);